//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogTechnically_Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BlogTechnically_Post()
        {
            this.BlogTechnically_Comment = new HashSet<BlogTechnically_Comment>();
        }
    
        public int PostId_PK { get; set; }
        public string Title { get; set; }
        public string PostContent { get; set; }
        public string PostedBy { get; set; }
        public System.DateTime PostedDate { get; set; }
        public string Status { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public int LoginId_FK { get; set; }
        public Nullable<int> CommentId_FK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogTechnically_Comment> BlogTechnically_Comment { get; set; }
        public virtual BlogTechnically_Post BlogTechnically_Post1 { get; set; }
        public virtual BlogTechnically_Post BlogTechnically_Post2 { get; set; }
        public virtual BlogTechnically_User BlogTechnically_User { get; set; }
    }
}
