

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Configuration file:     "DataModel\App.Config"
//     Connection String Name: "BlogTechnicallyEntities"
//     Connection String:      "metadata=res://*/BlogTechnically.csdl|res://*/BlogTechnically.ssdl|res://*/BlogTechnically.msl;provider=System.Data.SqlClient;provider connection string="data source=ANANTH-PC\HOMESQL;initial catalog=BlogTechnically;integrated security=True;MultipleActiveResultSets=True;App=EntityFramework""
// ------------------------------------------------------------------------------------------------

// ------------------------------------------------------------------------------------------------
// Failed to load provider "System.Data.EntityClient" - Unable to find the requested .Net Framework Data Provider.  It may not be installed.
// ------------------------------------------------------------------------------------------------

