//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogTechnically_Comment
    {
        public int CommentId_PK { get; set; }
        public Nullable<int> LoginId_FK { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CommentedDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> PostId_FK { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual BlogTechnically_Post BlogTechnically_Post { get; set; }
        public virtual BlogTechnically_User BlogTechnically_User { get; set; }
    }
}
