//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogTechnically_Category
    {
        public int CategoryId_PK { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Active { get; set; }
        public int LoginId_FK { get; set; }
    
        public virtual BlogTechnically_User BlogTechnically_User { get; set; }
    }
}
