//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogTechnically_Profile
    {
        public int ProfileId_PK { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public byte[] ProfilePicture { get; set; }
        public Nullable<int> LoginId_FK { get; set; }
        public string AboutMe { get; set; }
        public string MobileNumber { get; set; }
    
        public virtual BlogTechnically_User BlogTechnically_User { get; set; }
    }
}
