//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogTechnically_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BlogTechnically_User()
        {
            this.BlogTechnically_Category = new HashSet<BlogTechnically_Category>();
            this.BlogTechnically_Comment = new HashSet<BlogTechnically_Comment>();
            this.BlogTechnically_Post = new HashSet<BlogTechnically_Post>();
            this.BlogTechnically_Profile = new HashSet<BlogTechnically_Profile>();
            this.BlogTechnically_Token = new HashSet<BlogTechnically_Token>();
        }
    
        public int LoginId_PK { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int RoleId_FK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogTechnically_Category> BlogTechnically_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogTechnically_Comment> BlogTechnically_Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogTechnically_Post> BlogTechnically_Post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogTechnically_Profile> BlogTechnically_Profile { get; set; }
        public virtual BlogTechnically_Role BlogTechnically_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogTechnically_Token> BlogTechnically_Token { get; set; }
    }
}
